// Generated by https://quicktype.io

export interface CurrencyAPIResponse {
    meta: Meta;
    data: Data;
}

export interface Data {
    COP: Cop;
}

export interface Cop {
    code:  string;
    value: number;
}

export interface Meta {
    last_updated_at: string;
}
