// Generated by https://quicktype.io

export enum TiposVehiculo{
    carros = 'carros',
    motos = 'motos',
    camiones= 'caminhoes'
}

export interface Marca {
    codigo: string;
    nome:   string;
}

export interface Modelo {
    codigo: string;
    nome:   string;
}

export interface Anos{
    codigo: string;
    nome: string;
}

export interface Modelos{
    modelos: Modelo[];
    anos: Anos[];
}


export interface DataForm{
    tipo: TiposVehiculo;
    marca: string;
    modelo: string;
    anos: string;
}


export interface Options{
    codigo: string;
    nome: string;
}

// Generated by https://quicktype.io

export interface VehicleInfo {
    TipoVeiculo:      number;
    Valor:            string;
    Marca:            string;
    Modelo:           string;
    AnoModelo:        number;
    Combustivel:      string;
    CodigoFipe:       string;
    MesReferencia:    string;
    SiglaCombustivel: string;
}
